name: timbertrack_mill_app
description: Timbertrack Mill Flutter Application
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.0.5
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button2: ^1.9.2
  dynamic_text_highlighting:
    git: https://github.com/blakewood84/dynamic_text_highlighting.git
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  form_validator: ^1.0.3
  intl: ^0.17.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  simple_forms:
    git: https://github.com/Flutter-Postal-Service/simple_forms
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
